# whitelist
branches:
  only:
    - master
    - gh-pages

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo add-apt-repository -y ppa:marutter/c2d4u3.5
  - sudo apt-get update
  - curl -L -O https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
  - which pandoc
  - which pandoc-citeproc
  - pandoc --version
  - sudo apt-get install r-base
  - sudo apt-get install tree
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - Rscript -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "revealjs", "latticeExtra", "gdata"), type = "source", repos = "http://cran-r.c3sl.ufpr.br/")'
  - Rscript -e 'devtools::install_github("yihui/knitr")'
  - Rscript -e 'devtools::install_github("rstudio/rmarkdown")'

# build site

before_script:
  - rm -rf figures

script:
  - Rscript -e 'rmarkdown::render_site()'
